### ISSUE TITLE
Video Support

### ISSUE THREAD

**Issue by BenjaminDavison** [tinusn/cloudinary-angular#1]
Heya, thanks for the angular version of the lib

Have you managed to get video support working? I see some video related code in the repo, but have not been able to see if it works.

Thanks,

Ben

**Comment by tinusn** [comment]
I have not actually. The video stuff you see in there is there because its a copy of the jquery source where everything jquery has been removed. It should be a simple thing to add video support though.

If I get the time I'll look at it, otherwise you are more than welcome to provide a pull request.

**Comment by tinusn** [comment]
Done.

Just released a version with video support.

**Comment by BenjaminDavison** [comment]
Hah awesome! I was actually just about to come here and said I had done the same thing :dancer: 

Yours is better, as mine was a bit of a copy and paste job that just renamed a few things.
